0506/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/', views.recommended, name='recommended'),
]

0506/pjt09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

0506/movies/models.py
from django.db import models

class Genre(models.Model):
    name = models.CharField(max_length=50)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)

0506/movies/forms.py
from django import forms

# Create your forms here.

0506/movies/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.views.decorators.http import require_safe, require_http_methods, require_POST

from .models import Movie, Genre
import random

@require_safe
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


@require_safe
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


@require_http_methods(['GET', 'POST'])
def recommended(request):
    if request.method == 'POST':
        selected = request.POST.getlist('test')
        if len(selected) >= 3:
            size = [4, 3, 3]
        elif len(selected) == 2:
            size = [5, 5]
        elif len(selected) == 1:
            size = [10]

        result = []
        for i in range(len(selected)):
            movies = Movie.objects.filter(genres=selected[i])
            movies = list(movies)
            if len(movies) < size[i]:
                result.extend(movies)
            else:
                select = random.sample(range(len(movies)), size[i])

                for j in range(size[i]):
                    if movies[select[j]] not in result:
                        result.append(movies[select[j]])
        
        while len(result) < 10:
            num = random.randint(1, 100)
            movie = Movie.objects.get(pk=num)
            if movie not in result:
                result.append(movie)

        context = {
            'movies': result
        }
        return render(request, 'movies/recommended.html', context)
    
    elif request.method == 'GET':
        genres = Genre.objects.all()
        context = {
            'genres': genres
        }
        return render(request, 'movies/genre.html', context)

0506/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="text-center">

        <h1 class="my-3">DETAIL</h1>
        <hr>
        <div>
            <img src="{{ movie.poster_path }}" alt="" class="img-fluid">
        </div>
        <hr>

        <h4 class="my-3">{{ movie.title }}</h4>
        <p>개봉일 : <img src="https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1576470996/noticon/ln5xivnzmcq8yzejnsub.png" alt="" style="width: 15px"> {{ movie.release_date }}</p>
        <p>평점 : <img src="https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1609287743/noticon/oyo23yrstcp0rbd4uiqp.png" alt="" style="width: 15px"> {{ movie.vote_average }}</p>
        <p>내용 : {{ movie.overview }}</p>
    </div>
{% endblock %}

0506/movies/templates/movies/genre.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
    <h1 class="my-3 text-center">장르를 선택해주세요</h1>
    <p class="text-center text-secondary">(최대 3개...)</p>


    <form action="{% url 'movies:recommended' %}" method="POST" class="my-3 text-center">
        {% csrf_token %}
        <hr>
        <div class="container" style="width: 600px;">
            <div class="row text-center">
                {% for genre in genres %}
                <div class="form-check col-3">
                    <input type="checkbox" value="{{ genre.id }}" class="btn-check" id="{{genre.id}}" autocomplete="off" name="test" >
                    <label class="btn btn-outline-primary mx-1 my-1" for="{{genre.id}}" style="box-sizing: border-box; width: 130px;">{{ genre.name }}</label><br>
                </div>
                {% endfor %}
            </div>
        </div>
        <hr>
        <input type="submit" class="btn btn-primary my-3">
    </form>
    <div class="text-center">
        <a href="{% url 'movies:index' %}" class="btn btn-secondary">BACK</a>
    </div>
{% endblock content %}

0506/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Movies</h1>
  <hr>
  <div class="row row-cols-2 row-cols-lg-4 g-4">
    {% for movie in movies %}
    <div class="col">
      <div class="card">
        <img src="{{ movie.poster_path }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title img-fluid"><img src="https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1575057793/noticon/e4eukig4eptfib2pwhvo.svg" alt="" style="width: 15px;"> <a href="{% url 'movies:detail' movie.pk %}" class="text-decoration-none text-black">{{ movie.title }}</a></h5>
          <p class="card-text">
            <p><img src="https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1609287743/noticon/oyo23yrstcp0rbd4uiqp.png" alt="" style="width: 15px;"> {{ movie.vote_average }}</p>
            {{ movie.overview|truncatechars:80 }}
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}

0506/movies/templates/movies/recommended.html
{% extends 'base.html' %}

{% block content %}
  <h1>Recommended</h1>
  <hr>
  <div class="row row-cols-2 row-cols-lg-4 g-4">
    {% for movie in movies %}
    <div class="col">
      <div class="card">
        <img src="{{ movie.poster_path }}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title img-fluid"><img src="https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1575057793/noticon/e4eukig4eptfib2pwhvo.svg" alt="" style="width: 15px;"> <a href="{% url 'movies:detail' movie.pk %}" class="text-decoration-none text-black">{{ movie.title }}</a></h5>
          <p class="card-text">
            <p><img src="https://noticon-static.tammolo.com/dgggcrkxq/image/upload/v1609287743/noticon/oyo23yrstcp0rbd4uiqp.png" alt="" style="width: 15px;"> {{ movie.vote_average }}</p>
            {{ movie.overview|truncatechars:80 }}
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}