0506/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

0506/community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

0506/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/', views.recommended, name='recommended'),
]

0506/pjt09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

0506/templates/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>Document</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a href="{% url 'movies:index' %}" class="navbar-brand h1 my-2 mx-3">Movie</a>
      {% if user.is_authenticated %}
        <h3 class="text-light mx-3 my-auto">Hello, {{ user.username }}</h3>
      {% endif %}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <div class="container d-flex justify-content-end">
          {% if user.is_authenticated %}
          <a href="{% url 'accounts:profile' user %}" class="mx-2 my-auto btn btn-secondary">내 프로필<a>
          <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Logout" class="mx-2 my-auto btn btn-danger">
          </form>
          <a href="{% url 'movies:index'%}" class="mx-2 my-auto btn btn-primary nav-item">Movie</a>
          <a href="{% url 'community:index'%}" class="mx-2 my-auto btn btn-primary nav-item">Community</a>
          <a href="{% url 'community:create'%}" class="mx-2 my-auto btn btn-primary nav-item">New Review</a>
          <a href="{% url 'movies:recommended'%}" class="mx-2 my-auto btn btn-primary nav-item">Recommended</a>
          {% else %}
          <a href="{% url 'accounts:signup' %}" class="mx-2 my-auto btn btn-primary nav-item">Signup</a>
          <a href="{% url 'accounts:login' %}" class="mx-2 my-auto btn btn-primary nav-item">Login</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  {% block script %}{% endblock script %}
</body>
</html>