0415/EitherGame_Django/balance_game/BALANCEGAME/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votes/', include('votes.urls')),
]

0415/EitherGame_Django/balance_game/votes/urls.py
from django.urls import path
from . import views


app_name = 'votes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
]

0415/EitherGame_Django/balance_game/votes/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Vote(models.Model):
    title = models.CharField(max_length=20)
    Issue_a = models.CharField(max_length=20)
    Issue_b = models.CharField(max_length=20)
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    vote = models.ForeignKey(Vote, on_delete=models.CASCADE)
    
    class Voting(models.TextChoices):
        A = 'A'
        B = 'B'
        
    voting = models.CharField(max_length=1, choices=Voting.choices)
    content = models.CharField(max_length=100)

0415/EitherGame_Django/balance_game/votes/forms.py
from django import forms
from .models import Vote, Comment


class VoteForm(forms.ModelForm):

    class Meta:
        model = Vote
        fields = '__all__'
        


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('vote',)

0415/EitherGame_Django/balance_game/votes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import require_POST
from django.db.models import Count
from .models import Vote, Comment
from .forms import VoteForm, CommentForm

# Create your views here.
def index(request):
    votes = Vote.objects.order_by('-pk')
    context = {
        'votes' : votes,
    }
    return render(request, 'votes/index.html', context)

def detail(request, pk):
    vote = get_object_or_404(Vote, pk=pk)
    comment_form = CommentForm()
    comments = vote.comment_set.order_by('-pk')
    count_a = len(comments.filter(voting='A'))
    count_b = len(comments.filter(voting='B'))
    total = count_a + count_b
    if total == 0:
        voted_a = 0
        voted_b = 0
    else:
        voted_a = count_a / total * 100
        voted_b = count_b / total * 100

    # print('여기다', voted_a, voted_b)
    # vote_rate_a = Vote.objects.aggregate(Count(comments.)/Count(vote.pk)*100).get(vote_id=pk)
    # vote_rate_b = Vote.objects.aggregate(Count(vote.Issue_b)/Count(vote.pk)*100).get(vote_id=pk)
    context = {
        'vote' : vote,
        'comment_form' : comment_form,
        'comments' : comments,
        # 'vote_rate_a' : vote_rate_a,
        # 'vote_rate_b' : vote_rate_b,
        'voted_a' : voted_a,
        'voted_b' : voted_b,
    }
    return render(request, 'votes/detail.html', context)

def create(request):
    if request.method == 'POST':
        form = VoteForm(request.POST)
        if form.is_valid():
            vote = form.save()
            return redirect('votes:detail', vote.pk)
    else:
        form = VoteForm()
    context = {
        'form' : form,
    }
    return render(request, 'votes/create.html', context)

@require_POST
def comment_create(request, pk):
    vote = get_object_or_404(Vote, pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.vote = vote
        comment.save()
    return redirect('votes:detail', vote.pk)

0415/EitherGame_Django/balance_game/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="container">
    
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

0415/EitherGame_Django/balance_game/votes/templates/votes/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1 class="text-center">CREATE</h1>
  <form action="{% url 'votes:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn_primary" value='Submit'>
  </form>
  <hr>
  <a href="{% url 'votes:index' %}">[BACK]</a>
{% endblock content %}

0415/EitherGame_Django/balance_game/votes/templates/votes/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h3 class='text-center'>DETAIL</h3>
  <a class="btn btn-success" href="{% url 'votes:index' %}">[BACK]</a>
  <hr>
  <h1 class='text-center'>{{ vote.title }}</h1>
  <p>A : {{ vote.Issue_a }} : {{ voted_a }}%</p>
  <p>B : {{ vote.Issue_b }} : {{ voted_b }}%</p>
  <div class="container">
    <div class="row">
      <span class="text-start fs-5 fw-bolder text-danger">A : {{ vote.Issue_a }}</span>
      <span class="text-end fs-5 fw-bolder text-primary">{{ vote.Issue_b }} : B</span>
    </div>
    <div class="row">
      <div class="progress">
        <div class="progress-bar-striped progress-bar-animated bg-danger" role="progressbar" style="width: {{ voted_a }}%"  aria-valuemin="0" aria-valuemax="100"></div>
        <div class="progress-bar-striped progress-bar-animated bg-primary" role="progressbar" style="width: {{ voted_b }}%"  aria-valuemin="0" aria-valuemax="100"></div>
      </div>
    </div>
  </div>
  <hr>
  <br>
  <h3>댓글 작성</h3>
  <form action="{% url 'votes:comment_create' vote.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <input type="submit" class="btn btn-warning">
  </form>

  <hr>
  <br>
  <h3>댓글 목록</h3>

  {% for comment in comments %}
    {% if comment.voting == 'A' %}
      <div class="alert alert-danger" role="alert">
        {{ comment.content }}
      </div>
    {% endif %}
    {% if comment.voting == 'B' %}
      <div class="alert alert-primary" role="alert">
        {{ comment.content }}
      </div>
    {% endif %}
    <hr>
  {% endfor %}
  <div class="container height=30"></div>>

{% endblock content %}

0415/EitherGame_Django/balance_game/votes/templates/votes/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">Either Game</h1>
  <a href="{% url 'votes:create' %}" class="">[CREATE]</a>
  <hr>
  {% for vote in votes %}
    <p>{{ vote.pk }} : <a href="{% url 'votes:detail' vote.pk %}">{{ vote.title }}</a></p>
    <hr>
  {% endfor %}
{% endblock content %}